# Generated by Django 4.1.1 on 2022-10-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_in',
            old_name='user_name',
            new_name='username',
        ),
    ]
